import type { ComparisonReport, WidthWatchReport } from "./types.js";
import { getReportIssues } from "./report-issues.js";

export function generateHtmlReport(input: WidthWatchReport | ComparisonReport): string {
  const normalizeReport = (report: WidthWatchReport): WidthWatchReport => report.issues ? report : { ...report, issues: getReportIssues(report) };
  const comparison = "candidate" in input
    ? { ...input, baseline: normalizeReport(input.baseline), candidate: normalizeReport(input.candidate) }
    : null;
  const report = comparison ? comparison.candidate : normalizeReport(input as WidthWatchReport);
  const comparisonState = comparison ? (!comparison.valid ? "comparison invalid" : comparison.passed ? "comparison passed" : "regression found") : "scan complete";
  const statusClass = comparison && (!comparison.valid || !comparison.passed) ? "failed" : "";
  const changedDiffs = comparison?.diffs.filter((diff) => diff.changedPixels > 0).length ?? 0;
  const hasDiffImages = comparison?.diffs.some((diff) => Boolean(diff.diffScreenshot)) ?? false;
  const ranges = comparison?.regressionRanges ?? report.issueRanges ?? [];
  const affectedWidths = comparison ? new Set(comparison.regressions.map((issue) => issue.width)).size : 0;
  const rangeHtml = ranges.length
    ? `<div class="range-list"><h2>${comparison ? "Observed regression ranges" : "Observed issue ranges"}</h2>${ranges.map((range) => `<button data-range-width="${range.from}"><span><i class="sev ${range.severity}"></i>${escapeHtml(range.kind)}</span><b>Observed at ${range.from === range.to ? `${range.from}px` : `${range.from}—${range.to}px`}</b><small>Sampled widths: ${range.sampledWidths.join(", ")}px${range.cleanBefore !== undefined ? ` · ${range.cleanBefore}px clean` : ""}${range.cleanAfter !== undefined ? ` · ${range.cleanAfter}px clean` : ""} · ${escapeHtml(range.elements[0]?.selector ?? range.message)}</small></button>`).join("")}</div>`
    : "";
  const validationHtml = comparison?.validationErrors.length
    ? `<div class="validation"><strong>Comparison invalid</strong>${comparison.validationErrors.map((error) => `<p>${escapeHtml(error.message)}</p>`).join("")}</div>`
    : "";
  const payload = JSON.stringify({ report, comparison }).replaceAll("<", "\\u003c").replaceAll("\u2028", "\\u2028").replaceAll("\u2029", "\\u2029");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%230a0c09'/%3E%3Cpath d='M10 18l9 30 13-22 13 22 9-30' fill='none' stroke='%23c6ff3d' stroke-width='6' stroke-linejoin='round'/%3E%3C/svg%3E">
  <title>WidthWatch · ${escapeHtml(report.title || report.url)}</title>
  <style>
    :root{color-scheme:dark;--ink:#f3f5ef;--muted:#8d9488;--line:#2a3029;--acid:#c6ff3d;--error:#ff5c57;--warn:#ffc85a;--surface:#111410;--panel:#171b16}
    *{box-sizing:border-box}body{margin:0;background:#0a0c09;color:var(--ink);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}button,input{font:inherit}
    header{min-height:64px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:10px 28px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#0a0c09e8;backdrop-filter:blur(14px);z-index:5}
    .brand{font-weight:800;letter-spacing:-.04em;font-size:18px}.brand i{color:var(--acid);font-style:normal}.status{color:var(--muted)}.status b{color:var(--acid)}.status.failed,.status.failed b{color:var(--error)}
    .header-actions{display:flex;align-items:center;gap:16px}.jump{border:1px solid var(--error);background:transparent;color:var(--error);padding:9px 12px;cursor:pointer}.jump:hover,.jump:focus-visible{background:var(--error);color:#0a0c09}
    main{display:grid;grid-template-columns:minmax(0,1fr) 340px;min-height:calc(100vh - 64px)}.workspace{padding:28px;min-width:0}.inspector{border-left:1px solid var(--line);padding:24px;overflow:auto;max-height:calc(100vh - 64px);position:sticky;top:64px}
    .meta{display:flex;gap:24px;color:var(--muted);margin-bottom:28px;flex-wrap:wrap}.meta strong{color:var(--ink)}.frame-meta{display:flex;gap:20px;min-height:24px;color:var(--muted);margin:-8px 0 14px}.frame-meta strong{color:var(--ink)}
    .timeline{position:relative;height:104px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin-bottom:24px}.track{position:absolute;left:0;right:0;top:48px;height:2px;background:var(--line);pointer-events:none}.timeline-hit{position:absolute;inset:0;width:100%;border:0;background:transparent;cursor:crosshair;z-index:4}.timeline-hit:focus-visible{outline:2px solid var(--acid);outline-offset:3px}.tick{position:absolute;top:0;width:0;height:100%;pointer-events:none;z-index:2}.tick:before{content:"";position:absolute;left:-5px;top:43px;width:8px;height:8px;border:2px solid var(--acid);border-radius:50%;background:#0a0c09}.tick.captured:before{left:-1px;top:31px;width:2px;height:34px;border:0;border-radius:0;background:var(--acid)}.tick.error:before{border-color:var(--error)}.tick.captured.error:before{background:var(--error);height:46px;top:25px}.tick.warning:before{border-color:var(--warn)}.tick.captured.warning:before{background:var(--warn)}.tick span{display:none;position:absolute;top:73px;left:0;transform:translateX(-50%);color:var(--muted);font-size:11px;white-space:nowrap;background:#0a0c09;padding:1px 4px}.tick.endpoint:not(.clustered) span,.tick.has-issue:not(.clustered) span,.tick.selected span,.tick.hovered span{display:block}.tick.endpoint-start span{transform:none}.tick.endpoint-end span{transform:translateX(-100%)}.tick.selected span,.tick.hovered span{color:var(--ink);z-index:3}.timeline-tooltip{position:absolute;top:5px;z-index:6;transform:translateX(-50%);background:var(--panel);border:1px solid var(--line);color:var(--ink);padding:5px 8px;font-size:10px;white-space:nowrap;pointer-events:none}.timeline-tooltip[hidden]{display:none}
    .viewer{display:grid;place-items:start center;min-height:560px;overflow:auto;background-color:#0d100c;background-image:linear-gradient(#171b16 1px,transparent 1px),linear-gradient(90deg,#171b16 1px,transparent 1px);background-size:20px 20px;padding:28px}.diff-unavailable{align-self:center;border:1px solid var(--line);background:#0a0c09;padding:18px;color:var(--muted)}
    .shot-wrap{position:relative;box-shadow:0 20px 70px #0009;transition:width .2s ease}.shot{display:block;width:100%;height:auto}.overlay{position:absolute;border:2px solid var(--error);background:#ff5c5722;pointer-events:none}.overlay.warning{border-color:var(--warn);background:#ffc85a22}
    h1{font:700 26px/1.1 system-ui,sans-serif;letter-spacing:-.04em;margin:0 0 8px}.url{color:var(--muted);word-break:break-all;margin-bottom:28px}.summary{display:grid;grid-template-columns:repeat(3,1fr);border-block:1px solid var(--line);margin-bottom:24px}.summary div{padding:14px 0}.summary strong{font-size:22px;display:block}.summary span{font-size:11px;color:var(--muted);text-transform:uppercase}.issues{display:grid;gap:1px;background:var(--line)}
    .issue{background:#0a0c09;padding:15px;border:0;color:inherit;text-align:left;cursor:pointer}.issue:hover,.issue.active{background:var(--panel)}.issue:focus-visible{outline:2px solid var(--acid);outline-offset:-2px}.issue small{color:var(--muted)}.issue b{display:block;margin:3px 0}.sev{width:7px;height:7px;border-radius:50%;display:inline-block;background:var(--acid);margin-right:7px}.sev.error{background:var(--error)}.sev.warning{background:var(--warn)}
    .empty{color:var(--muted);padding:24px 0}.legend{display:flex;gap:18px;color:var(--muted);font-size:11px;margin-top:10px}.legend i{display:inline-block;vertical-align:-1px;margin-right:6px}.legend .probe-key{width:8px;height:8px;border:2px solid var(--acid);border-radius:50%}.legend .capture-key{width:2px;height:16px;background:var(--acid)}.legend .issue-key{width:8px;height:8px;border-radius:50%;background:var(--error)}.validation{border:1px solid var(--error);background:#ff5c5710;padding:14px;margin-bottom:18px}.validation strong{color:var(--error)}.validation p{color:var(--muted);margin:6px 0 0}.view-tabs{display:flex;gap:1px;margin:0 0 18px;background:var(--line);width:max-content}.view-tabs button{border:0;background:var(--surface);color:var(--muted);padding:9px 14px;cursor:pointer}.view-tabs button.active{background:var(--acid);color:#0a0c09}.range-list{margin-top:26px;border-top:1px solid var(--line);padding-top:18px}.range-list h2{font:600 11px/1.2 ui-monospace,monospace;text-transform:uppercase;color:var(--muted);letter-spacing:.08em}.range-list button{display:grid;grid-template-columns:1fr auto;width:100%;gap:4px 12px;border:0;border-bottom:1px solid var(--line);padding:12px 0;background:transparent;color:var(--ink);text-align:left;cursor:pointer}.range-list button:hover{color:var(--acid)}.range-list small{grid-column:1/3;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.range-list span{font-size:11px;color:var(--muted)}
    @media(max-width:900px){main{grid-template-columns:1fr}.inspector{position:static;max-height:none;border-left:0;border-top:1px solid var(--line)}.workspace{padding:16px}.viewer{min-height:420px;padding:12px}header{padding:10px 16px}.status{display:none}}
    @media(prefers-reduced-motion:reduce){*{transition:none!important}}
  </style>
</head>
<body>
<header><div class="brand">width<i>watch</i></div><div class="header-actions">${comparison?.regressions.length ? '<button class="jump" id="firstRegression">First regression →</button>' : ""}<div class="status ${statusClass}"><b>●</b> ${comparisonState}</div></div></header>
<main><section class="workspace"><div class="meta"><span>range <strong>${report.range.min}—${report.range.max}px</strong></span><span>captures <strong>${report.frames.length}</strong></span>${report.sampling?.strategy.includes("two-pass") ? `<span>probes <strong>${report.probes?.length ?? report.sampling.discoveryWidths.length}</strong></span>` : ""}<span>duration <strong>${(report.durationMs / 1000).toFixed(1)}s</strong></span>${comparison?.settings ? `<span>threshold <strong>${(comparison.settings.maxDiffRatio * 100).toFixed(2)}%</strong></span><span>escalated <strong>${comparison.escalated?.length ?? 0}</strong></span><span>de-escalated <strong>${comparison.deescalated?.length ?? 0}</strong></span><span>resolved <strong>${comparison.resolved?.length ?? 0}</strong></span>` : ""}</div>${comparison ? `<div class="view-tabs" id="viewTabs"><button data-view="baseline">Baseline</button><button class="active" data-view="candidate">Candidate</button>${hasDiffImages ? '<button data-view="diff">Diff</button>' : ""}</div>` : ""}<div class="timeline" id="timeline"><div class="track"></div><div id="markerLayer"></div><button class="timeline-hit" id="timelineHit" type="button" role="slider" aria-label="Responsive width probes" aria-orientation="horizontal" aria-valuemin="${report.range.min}" aria-valuemax="${report.range.max}"></button><output class="timeline-tooltip" id="timelineTooltip" hidden></output></div><div class="frame-meta" id="frameMeta"></div><div class="viewer"><div class="diff-unavailable" id="diffUnavailable" hidden></div><div class="shot-wrap" id="shotWrap"><img class="shot" id="shot" alt="Responsive capture"><div id="overlays"></div></div></div><div class="legend"><span><i class="probe-key"></i>geometry probe</span><span><i class="capture-key"></i>visual evidence</span><span><i class="issue-key"></i>issue detected</span></div></section>
<aside class="inspector"><h1>${escapeHtml(report.title || "Untitled page")}</h1><div class="url">${escapeHtml(report.url)}</div><div class="summary"><div><strong>${comparison ? ranges.length : report.summary.errors}</strong><span>${comparison ? "regression types" : "errors"}</span></div><div><strong>${comparison ? affectedWidths : report.summary.warnings}</strong><span>${comparison ? "affected widths" : "warnings"}</span></div><div><strong>${comparison ? changedDiffs : report.summary.sampledWidths}</strong><span>${comparison ? "changed frames" : "probes"}</span></div></div>${validationHtml}<div class="issues" id="issues"></div>${rangeHtml}</aside></main>
<script>const DATA=${payload};
const report=DATA.report,comparison=DATA.comparison,timeline=document.querySelector('#timeline'),markerLayer=document.querySelector('#markerLayer'),timelineHit=document.querySelector('#timelineHit'),timelineTooltip=document.querySelector('#timelineTooltip'),shot=document.querySelector('#shot'),shotWrap=document.querySelector('#shotWrap'),diffUnavailable=document.querySelector('#diffUnavailable'),issues=document.querySelector('#issues'),overlays=document.querySelector('#overlays'),frameMeta=document.querySelector('#frameMeta'),probes=report.probes?.length?report.probes:report.frames,markerElements=[];let selected=0,hovered=-1,view='candidate';
function probesFor(value){return value.probes?.length?value.probes:value.frames}
function frameAt(value,width){return value.frames.find(item=>item.width===width)}
function reportIssues(value){return value.issues||[]}
function identity(item){return item.kind+':'+item.elements.map(element=>element.selector).sort().join('|')}
function occurrence(item){return item.width+':'+identity(item)}
function issuesAt(probe){if(!comparison)return reportIssues(report).filter(item=>item.width===probe.width);if(view==='baseline')return reportIssues(comparison.baseline).filter(item=>item.width===probe.width);return comparison.regressions.filter(item=>item.width===probe.width)}
function severity(probe){const list=comparison?comparison.regressions.filter(item=>item.width===probe.width):reportIssues(report).filter(item=>item.width===probe.width);return list.some(item=>item.severity==='error')?'error':list.some(item=>item.severity==='warning')?'warning':''}
function severityChange(item){return comparison?.escalated?.find(change=>occurrence(change.candidate)===occurrence(item))}
function visualFrame(probe){const source=view==='baseline'&&comparison?comparison.baseline:report,frame=frameAt(source,probe.width),list=issuesAt(probe);if(view==='diff'&&comparison){const diff=comparison.diffs.find(item=>item.width===probe.width);return {...probe,...frame,screenshot:diff?.diffScreenshot||'',issues:list}}return {...probe,...frame,screenshot:frame?.screenshot||'',issues:list}}
function render(index){selected=Math.max(0,Math.min(index,probes.length-1));const probe=probes[selected],frame=visualFrame(probe),diff=comparison&&comparison.diffs.find(item=>item.width===probe.width),hasShot=Boolean(frame.screenshot),state=severity(probe);shot.hidden=!hasShot;shotWrap.hidden=!hasShot;diffUnavailable.hidden=hasShot;diffUnavailable.textContent=view==='diff'?'Diff image not generated for this sampled width.':'Detected during discovery; visual evidence was not captured at this width.';if(hasShot){shot.src=frame.screenshot;shot.alt=(view==='candidate'?'Candidate':view[0].toUpperCase()+view.slice(1))+' capture at '+frame.width+' pixels'}else{shot.removeAttribute('src')}shotWrap.style.width=Math.min(frame.width,shotWrap.parentElement.clientWidth-24)+'px';frameMeta.innerHTML='<span>viewport <strong>'+frame.width+'px</strong></span>'+(hasShot?'<span>evidence <strong>captured</strong></span>':'<span>evidence <strong>not captured</strong></span>')+(diff?'<span>changed <strong>'+(diff.ratio*100).toFixed(3)+'%</strong></span>':'');markerElements.forEach((element,itemIndex)=>{element.style.opacity=itemIndex===selected?'1':'.45';element.classList.toggle('selected',itemIndex===selected)});timelineHit.setAttribute('aria-valuenow',String(probe.width));timelineHit.setAttribute('aria-valuetext',probe.width+' pixels, '+(hasShot?'visual evidence captured':'geometry probe only')+(state?', '+state+' finding':''));issues.innerHTML='';overlays.innerHTML='';if(!frame.issues.length){issues.innerHTML='<div class="empty">'+(comparison?'No new regressions at this width.':'No deterministic issues at this width.')+'</div>'}
frame.issues.forEach((item,itemIndex)=>{const issueHasEvidence=item.evidence?item.evidence==='capture':hasShot,change=severityChange(item),changeLabel=change?' · escalated '+change.baseline.severity+'→'+change.candidate.severity:'',button=document.createElement('button');button.className='issue'+(itemIndex===0?' active':'');button.dataset.issueId=item.id;button.innerHTML='<small><i class="sev '+item.severity+'"></i>'+item.width+'px · '+item.kind+changeLabel+(issueHasEvidence?' · evidence captured':' · discovery only')+'</small><b>'+escapeText(item.message)+'</b><small>'+escapeText(item.elements.map(element=>element.selector).join(' · '))+'</small>';button.onclick=()=>{document.querySelectorAll('.issue').forEach(element=>element.classList.remove('active'));button.classList.add('active');draw(item,frame,hasShot&&issueHasEvidence)};issues.append(button)});if(frame.issues[0]){const first=frame.issues[0],firstHasEvidence=first.evidence?first.evidence==='capture':hasShot;draw(first,frame,hasShot&&firstHasEvidence)}}
function draw(item,frame,hasShot){overlays.innerHTML='';if(!hasShot)return;const scale=shot.clientWidth/frame.width;item.elements.forEach(element=>{const box=document.createElement('div');box.className='overlay '+item.severity;Object.assign(box.style,{left:element.rect.x*scale+'px',top:element.rect.y*scale+'px',width:element.rect.width*scale+'px',height:element.rect.height*scale+'px'});overlays.append(box)})}
function escapeText(value){const element=document.createElement('span');element.textContent=value;return element.innerHTML}
function markerPercent(width){return (width-report.range.min)/Math.max(1,report.range.max-report.range.min)*100}
function markerPixels(width){return markerPercent(width)/100*timeline.clientWidth}
function layoutMarkers(){const positions=probes.map(probe=>markerPixels(probe.width));markerElements.forEach((element,index)=>element.classList.toggle('clustered',positions.some((position,other)=>other!==index&&Math.abs(position-positions[index])<42)))}
function nearestIndex(clientX){const rect=timeline.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(clientX-rect.left)/Math.max(1,rect.width))),width=report.range.min+ratio*(report.range.max-report.range.min);return probes.reduce((best,probe,index)=>Math.abs(probe.width-width)<Math.abs(probes[best].width-width)?index:best,0)}
function showHover(index,clientX){if(hovered>=0)markerElements[hovered].classList.remove('hovered');hovered=index;markerElements[index].classList.add('hovered');const center=markerPixels(probes[index].width),cluster=probes.filter(probe=>Math.abs(markerPixels(probe.width)-center)<22),rect=timeline.getBoundingClientRect(),left=Math.max(48,Math.min(rect.width-48,clientX-rect.left));timelineTooltip.style.left=left+'px';timelineTooltip.textContent=(cluster.length>1?'Cluster: '+cluster.map(probe=>probe.width).join(' · '):probes[index].width)+'px';timelineTooltip.hidden=false}
probes.forEach((probe,index)=>{const captured=Boolean(frameAt(report,probe.width)),state=severity(probe),tick=document.createElement('div');tick.className='tick '+(captured?'captured ':'probe ')+state+(state?' has-issue':'')+(index===0?' endpoint endpoint-start':'')+(index===probes.length-1?' endpoint endpoint-end':'');tick.style.left=markerPercent(probe.width)+'%';tick.innerHTML='<span>'+probe.width+'</span>';markerLayer.append(tick);markerElements.push(tick)});layoutMarkers();
timelineHit.addEventListener('click',event=>render(nearestIndex(event.clientX)));timelineHit.addEventListener('pointermove',event=>showHover(nearestIndex(event.clientX),event.clientX));timelineHit.addEventListener('pointerleave',()=>{if(hovered>=0)markerElements[hovered].classList.remove('hovered');hovered=-1;timelineTooltip.hidden=true});timelineHit.addEventListener('keydown',event=>{let next=selected;if(event.key==='ArrowRight'||event.key==='ArrowUp')next+=1;else if(event.key==='ArrowLeft'||event.key==='ArrowDown')next-=1;else if(event.key==='PageDown')next+=5;else if(event.key==='PageUp')next-=5;else if(event.key==='Home')next=0;else if(event.key==='End')next=probes.length-1;else return;event.preventDefault();render(next)});
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{view=button.dataset.view;document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));render(selected)});function selectWidth(width,issueId){const index=probes.findIndex(probe=>probe.width===width);if(index>=0){render(index);if(issueId)requestAnimationFrame(()=>document.querySelector('[data-issue-id="'+CSS.escape(issueId)+'"]')?.focus())}}document.querySelectorAll('[data-range-width]').forEach(button=>button.onclick=()=>selectWidth(Number(button.dataset.rangeWidth)));const firstRegression=comparison&&comparison.regressions.find(item=>item.severity==='error')||comparison&&comparison.regressions[0];document.querySelector('#firstRegression')?.addEventListener('click',()=>selectWidth(firstRegression.width,firstRegression.id));render(firstRegression?Math.max(0,probes.findIndex(probe=>probe.width===firstRegression.width)):0);addEventListener('resize',()=>{layoutMarkers();render(selected)});</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}
